### PR TITLE
fix(playwright): Delete metadata from test name

### LINKED ISSUE #705: Metadata appear is in test name
**Describe the bug**
Metadata should not be in test name in report

**To Reproduce**
Preconditions: 
1. version of allure-js [2.3.0](https://github.com/allure-framework/allure-js/releases/tag/v2.3.0)
2. pass metadata in test title

1. run the test
3. generate allure report

**Expected behavior**
Metadata passed in title is NOT appear in test name in report

**Actual behavior**
Metadata appear in test name in report

**Screenshots**
Снимок экрана 2023-06-19 в 19 48 26

**Versions:**
 - version of allure-js [2.3.0](https://github.com/allure-framework/allure-js/releases/tag/v2.3.0)

**Test:**
```
import { test } from '@integration-tests/fixtures/setup.fixture';
import { expect } from '@playwright/test';

test.only('Metadata in test @allure.id=1111', async () => {
  expect(true).toBeTruthy();
});

```

### PR DESCRIPTION
**Pull request by vovsemenv**
### Context

fixes #705
#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by vovsemenv** [comment]
@lunin-vadim can you also take a look?

**Review by baev — APPROVED** [review]

**Comment by lunin-vadim** [comment]
Looks good

**Comment by vovsemenv** [comment]
@baev merge and release please

**Comment by lunin-vadim** [comment]
@baev @vovsemenv  merge and release please

**Pull request merged**
