### PR TITLE
added support for links to issues and tms for codeceptjs

### PR DESCRIPTION
**Pull request by guiyomh**
### Context
 I want use allure xray plugin, but I must configure link on my test.
So, I propose this PR to set up the links to issue and tms.

#### Issue Link

Setup codeceptjs plugin with: 

```diff
const { setHeadlessWhen, setCommonPlugins } = require("@codeceptjs/configure");
const path = require("path");

setCommonPlugins();

module.exports.config = {
  tests: "./**/*.test.js",
  output: path.resolve(__dirname, "./output"),
  plugins: {
    allure: {
      enabled: true,
      require: "allure-codeceptjs",
+      issueURlTemplate: "https://example.qameta.io/allure-framework/allure-js/issues/%s",
    },
  },
};
```

```javascript
Feature("login-feature");
Scenario("login-scenario1", async () => {
  // your test
}).tag("@allure.issue:MY-ISSUE-82");
```

#### TMS Link

Setup codeceptjs plugin with: 

```diff
const { setHeadlessWhen, setCommonPlugins } = require("@codeceptjs/configure");
const path = require("path");

setCommonPlugins();

module.exports.config = {
  tests: "./**/*.test.js",
  output: path.resolve(__dirname, "./output"),
  plugins: {
    allure: {
      enabled: true,
      require: "allure-codeceptjs",
+      tmsURLTemplate: "https://example.qameta.io/allure-framework/allure-js/tests/%s",
    },
  },
};
```

```javascript
Feature("login-feature");
Scenario("login-scenario1", async () => {
  // your test
}).tag("@allure.tms:MY-TEST-CASE-64");
```

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by guiyomh** [comment]
@vovsemenv is this feature right for you?

**Comment by vovsemenv** [comment]
Hello @guiyomh! Looking good, but I have thoughts that this feature needs to be handled by the report-generator side of allure. I will add more detailed review later

**Comment by guiyomh** [comment]
You mean make a java plugin that does this job?

**Comment by vovsemenv** [comment]
yep

**Comment by guiyomh** [comment]
I think it's a good idea, but I don't know the plugin system very well.
I didn't see how to manage the priority between plugins. For example if I convert this feature to an allure2 plugin. It should be executed before the xray plugin, otherwise it doesn't make sense.

**Review by baev — CHANGES_REQUESTED** [review]
All good! Thanks for the contribution! 🚀

Maybe we should align the configuration with the other integrations? For example, in Allrue Codeception https://github.com/allure-framework/allure-codeception, we added support for different link types.

**Comment by baev** [comment]
@vovsemenv @guiyomh we'll add tags processing on the generator side for labels. Still, the links should be processed independently at the framework side because links require additional configuration (link patterns), and users may build an aggregated report from different tests, which my require different link patterns per test type.

**Comment by baev** [comment]
BTW for allure-cucumberjs we have the following config https://github.com/allure-framework/allure-js/tree/master/packages/allure-cucumberjs

We really need to try harder aligning simular features between the frameworks 🤪

**Comment by guiyomh** [comment]
If you want, I can do other PR to align other framework on this MR.

**Comment by baev** [comment]
fixed via #968

**Comment by baev** [comment]
@guiyomh thanks anyway!

**Pull request closed without merging**
