### PR TITLE
Fix allure-jest jest.retryTimes() bug

### LINKED ISSUE #922: allure-jest - test_retry event not handled properly
In our repository, we define jest configuration for automatic allure labels assignment.

#### jest.config.js
```js
/** @type {import('jest').Config} */
const config = {
  testEnvironment: 'allure-jest/node',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
};

module.exports = config;
```

#### jest.setup.js
```js
beforeEach(() => {
  allure.epic('some automatically calculated label');
});
```

And in most cases this setup works correctly.

When use allure-jest/node or allure-jest/jsdom environment, there is test [event handler](https://github.com/allure-framework/allure-js/blob/main/packages/allure-jest/src/AllureJest.ts#L92). In that handler on different stages of test-runner, allure-jest performs needed manipulations.

But in case of `jest.retryTimes` ([doc](https://jestjs.io/docs/jest-object#jestretrytimesnumretries-options)), jest-circus [dispatch](https://github.com/jestjs/jest/blob/main/packages/jest-circus/src/run.ts#L97) `test_retry` event, which is not handled by allure-jest environment properly.

#### Events dispatched by test-circus, with retryTimes and one failed test:
```shell
> setup
> add_hook (beforeEach)
> start_describe_definition

> add_test
### test is registred in allure-jest environment
### this.runningTests.set(newTestId, newTest);
### https://github.com/allure-framework/allure-js/blob/main/packages/allure-jest/src/AllureJest.ts#L166

> finish_describe_definition
> run_start
> run_describe_start
> test_start
> test_started
> hook_start (beforeEach)
> hook_success
> test_fn_start
> test_fn_failure
> test_done
### in handler test removed from allure-jest environment
### this.runningTests.delete(currentTestId);
### https://github.com/allure-framework/allure-js/blob/main/packages/allure-jest/src/AllureJest.ts#L250

> test_retry
> test_start
> test_started
> hook_start
### in new test run - there is no test registered in this.runningTests map 
### Exception has occurred: TypeError: Cannot read properties of undefined (reading 'applyMetadata')
###   at NodeEnvironment.handleAllureMetadata (/node_modules/allure-jest/src/AllureJest.ts:89:19)
###     at /node_modules/allure-jest/src/AllureJestApi.ts:28:16
###     ...
```

This exception produced in beforeEach hook, attempt to write metadata for test [here](https://github.com/allure-framework/allure-js/blob/main/packages/allure-jest/src/AllureJest.ts#L89):
```ts
    handleAllureMetadata(payload: { currentTestName: string; metadata: MetadataMessage }) {
      const currentTest = this.runningTests.get(payload.currentTestName)!;

      currentTest.applyMetadata(payload.metadata);
    }
```

`currentTest` is undefined, because after test failure in test_done handler test was deleted from `runningTests` map.

#### To Reproduce
minimal setup for reproduce this bug:
https://github.com/kriku/allure-jest-retry-times

```
npm install
npm test
```

or [check log in github actions](https://github.com/kriku/allure-jest-retry-times/actions/runs/8499949806/job/23281294484)

#### Expected behavior
On retry beforeEach hook have to work as on first try

### PR DESCRIPTION
**Pull request by kriku**
### Context
fixes #922

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure-js

### CODE REVIEW

**Comment by epszaw** [comment]
Hey, @kriku! Could you format the code using format and lint scripts from the project's root `package.json`?

**Review by epszaw — APPROVED** [review]

**Comment by kriku** [comment]
> Hey, @kriku! Could you format the code using format and lint scripts from the project's root `package.json`?

done ✅

**Comment by epszaw** [comment]
Good job there, @kriku!

**Comment by baev** [comment]
@kriku, this will be landed into the 3.0 release (ETA ~3 weeks). If you need it to be delivered sooner, we can do 2.15.2 early next week

**Pull request merged**
