### PR TITLE
feature(codeceptjs): feature to pass allure metadata through сodeceptjs tags

### PR DESCRIPTION
**Pull request by guiyomh**
### Context

The objective of this PR is to be able to manage the labels of pace via tags on the codeceptjs scenario.
for example:
```js
      Scenario('taggs', () => { 
        // my test
     }).tag('@slow')
        .tag('important')
        .tag('@owner:eroshenkoam')
        .tag('@layer:UI')
        .tag('@id:228')
        .tag('@story:aga')
        .tag('@epic:aga')
        .tag('@severity:critical');
   ```

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by vovsemenv** [comment]
Hello @guiyomh Thank you for the contribution. Its looks great overall.
I only have question about label syntax. In you examples you using `tag('@{labelType}:{labelValue}')` when we have other syntax used in [newman-reporter](https://github.com/allure-framework/allure-js/blob/master/packages/newman-reporter-allure/src/helpers.ts#L7) `/@allure.{labelType}:{labelValue}/`

Is there some reason to use new syntax or you can use already created one ??

**Comment by baev** [comment]
BTW Allure TestOps supports both `:` and `.`.

PS @vovsemenv maybe we can move the processing of the tags to the report generation phase as it has done for ATO?

**Comment by guiyomh** [comment]
@vovsemenv You can also use the tags to manage the labels on the scenarios. I made the changes to have the same syntax as for the newman plugin

**Comment by guiyomh** [comment]
@vovsemenv I also updated the readme. Does this change seem ok to you?

**Review by vovsemenv — APPROVED** [review]

**Comment by vovsemenv** [comment]
@guiyomh Everything good! Thank you so much for the contribution)

**Comment by guiyomh** [comment]
@vovsemenv thank, what is your release management process to tag a new version of this node package?

**Comment by vovsemenv** [comment]
@guiyomh today i want to add similar feature to playwright and release 2.2.0 with new features

**Pull request merged**
