### PR TITLE
Add writeExecutorInfo() method to AllureRuntime

### LINKED ISSUE #702: Allow customizing the ExecutorInfo from allure-js-commons
**Is your feature request related to a problem? Please describe.**

I'd like to make it possible to **customize executor information programmatically.**

**Describe the solution you'd like**

`allure-js-commons` should export `ExecutorInfo` from its `model.d.ts`.

Ideally, `AllureWriter` should provide `writeExecutorInfo()` method as well.

**Describe alternatives you've considered**

Copy & pasting the type definition and creating a side writer to that `executor.json`, huh? 🤨  😄 

**Additional context**

image

P. S. So, is there a good reason why `allure-js-commons` provides a method for writing down the environment info, but not the executor info?

### PR DESCRIPTION
**Pull request by noomorph**
### Context

Resolves #702.

> I'd like to make it possible to customize executor information programmatically, e.g.:

#### Checklist

- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by vovsemenv — APPROVED** [review]
Awesome job! Thank you.
Did you plan to bring it to the adapters itself like playwright, cucumber yourself ??

**Comment by vovsemenv** [comment]
ok, need to fix linter

**Comment by noomorph** [comment]
I'm working on it in the context of my project: jest-allure2-reporter.

**Comment by noomorph** [comment]
@vovsemenv PR passes.

**Review by baev — APPROVED** [review]

**Comment by noomorph** [comment]
Is there something missing here?

**Pull request closed without merging**
