### PR TITLE
fix(cucumberjs): support steps' attachments 

### LINKED ISSUE #688: Allure attachments are place outside the cucumber steps
Hello
**Describe the bug**
I use dependency
```
    "@cucumber/cucumber": "^9.1.2",
    "testcafe": "^2.6.0",
    "allure-cucumberjs": "2.3.0",
    "allure-commandline": "^2.1.0",
```
After passing the test and generating an allure, the attachments are displayed outside the steps

**To Reproduce**
```
import { Given, setWorldConstructor } from "@cucumber/cucumber"
import { CucumberAllureWorld } from "allure-cucumberjs"

SetWorldConstructor(CucumberAllureWorld)

Given(/my step/, async function () {
  await this.step("step can have anonymous body function", async function () {
    await this.label("label_name", "label_value")
    await this.attach(JSON.stringify({ foo: "bar "}), "application/json")
  })

  await this.step("by the way, body function can be arrow one", async (step) => {
    await step.label("label_name", "label_value")
    await step.attach(JSON.stringify({ foo: "bar "}), "application/json")
  })
})
```

**Expected behavior**
Attachments should be place inside is corresponding step.

**Actual behavior**
Steps attachments are empty and move to the end of the test.
allure-result json

```
{
  "uuid": "21cd2dc3-e414-48d1-a105-9af2b5bc8455",
  "historyId": "c5cbfaa5134b6c29281a2e3e2930af30",
  "status": "passed",
  "statusDetails": {},
  "stage": "pending",
  "steps": [
    {
      "status": "passed",
      "statusDetails": {},
      "stage": "pending",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1684483179754,
      "name": "A cat fact is recieved",
      "stop": 1684483179755
    }
  ],
  "attachments": [
    {
      "name": "attachment",
      "type": "application/json",
      "source": "7a89e88c-c33b-4515-b6de-8450df4f6c8f-attachment.json"
    }
  ],
```

**My suggestion:**
I noticed that the onAttachment function does not provide an option to add attachments to the step 
The line that needs to be changed: https://github.com/allure-framework/allure-js/blob/master/packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts#L359
```
        (currentStep ?? currentTest).addAttachment(fileName, {
            contentType: mediaType,
        }, attachmentFilename);
```
This solution adds attachments to the step, in case attachments have been added outside of the steps, then they are added down the allure

### PR DESCRIPTION
**Pull request by ilya2010ujl**
Closes #688

Please check linked issue to get more information about the problem

### Context
Allure attachments are place outside the cucumber steps

#### Checklist
- [X] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by baev — CHANGES_REQUESTED** [review]
Could you please add a test?

**Comment by ilya2010ujl** [comment]
Hello
Test:
```
import { Given, setWorldConstructor } from "@cucumber/cucumber"
import { CucumberAllureWorld } from "allure-cucumberjs"

SetWorldConstructor(CucumberAllureWorld)

Given(/my step/, async function () {
  await this.step("step can have anonymous body function", async function () {
    await this.label("label_name", "label_value")
    await this.attach(JSON.stringify({ foo: "bar "}), "application/json")
  })

  await this.step("by the way, body function can be arrow one", async (step) => {
    await step.label("label_name", "label_value")
    await step.attach(JSON.stringify({ foo: "bar "}), "application/json")
 })
```
After start run the command "allure serve"
ER: 
image

**Comment by epszaw** [comment]
> Hello Test:
> 
> ```
> import { Given, setWorldConstructor } from "@cucumber/cucumber"
> import { CucumberAllureWorld } from "allure-cucumberjs"
> 
> SetWorldConstructor(CucumberAllureWorld)
> 
> Given(/my step/, async function () {
>   await this.step("step can have anonymous body function", async function () {
>     await this.label("label_name", "label_value")
>     await this.attach(JSON.stringify({ foo: "bar "}), "application/json")
>   })
> 
>   await this.step("by the way, body function can be arrow one", async (step) => {
>     await step.label("label_name", "label_value")
>     await step.attach(JSON.stringify({ foo: "bar "}), "application/json")
>  })
> ```
> 
> After start run the command "allure serve" ER: image

Could you add a unit test (into the package) to cover the provided code?

**Comment by ilya2010ujl** [comment]
Can you please tell me if this is a required condition for the merge in the master? Or is it possible without unit tests?)

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@ilya2010ujl thanks!

**Pull request merged**
