### PR TITLE
Add support for content type video/mp4

### PR DESCRIPTION
**Pull request by QA-ler**
### Context
Just like in #487 the content type for video/mp4 is missing.
I had the same problem but instead I'm using Mocha via WDIO adding MP4 files generated by Puppeteer-Screen-Recorder

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@QA-ler thanks for the contribution! Please fix the build and address the CLA comment above

**Comment by QA-ler** [comment]
@baev fixed both issues

**Comment by baev** [comment]
@QA-ler thanks!

**Comment by QA-ler** [comment]
@baev Any idea when this will be released?

**Pull request merged**
