### PR TITLE
feat(allure-playwright): initial implementation for allure-playwright

### PR DESCRIPTION
**Pull request by pavelfeldman**
Fixes https://github.com/allure-framework/allure-js/issues/296, https://github.com/microsoft/playwright/issues/7034

This is initial implementation for Playwright reporter. I already booked `allure-playwright` npm package for it, please let me know who I should transfer ownership over it to. I did not push that package.

Please let me know what you think about it and I can add more tests for it.

### CODE REVIEW

**Comment by just-boris** [comment]
Hello!

Thanks for the PR! There are known build failures, will be fixed soon #298

**Comment by pavelfeldman** [comment]
I added a couple more tests.

**Comment by baev** [comment]
> I already booked `allure-playwright` npm package for it, please let me know who I should transfer ownership over it to. I did not push that package.

https://www.npmjs.com/~baev


Can we also add `language` and `framework` labels for each test?

**Comment by pavelfeldman** [comment]
> https://www.npmjs.com/~baev

Done.

> Can we also add language and framework labels for each test?

Done.

**Comment by pavelfeldman** [comment]
Tell me if I should kick myself out of the owners for `allure-playwright` or you want someone from Playwright team there.

**Comment by pavelfeldman** [comment]
Playwright v1.13 is out and I published this package as `experimental-allure-playwright` to let users try it out.

**Comment by mpuertao** [comment]
@baev  good day. When will the changes be approved?

**Comment by baev** [comment]
@pavelfeldman could you please fix the build?

**Comment by pavelfeldman** [comment]
You probably want to merge https://github.com/allure-framework/allure-js/pull/298, otherwise current master is broken:

```bash
allure-jasmine: test/label.test.ts(10,14): error TS2339: Property 'describe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/label.test.ts(11,16): error TS2339: Property 'it' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(10,15): error TS2339: Property 'describe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(11,17): error TS2339: Property 'it' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(25,15): error TS2339: Property 'describe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(26,17): error TS2339: Property 'it' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(40,15): error TS2339: Property 'describe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(41,17): error TS2339: Property 'xit' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(55,15): error TS2339: Property 'xdescribe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/status.test.ts(56,17): error TS2339: Property 'it' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/step.test.ts(10,15): error TS2339: Property 'describe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/step.test.ts(11,17): error TS2339: Property 'it' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/step.test.ts(35,15): error TS2339: Property 'describe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/step.test.ts(36,17): error TS2339: Property 'it' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/step.test.ts(74,15): error TS2339: Property 'describe' does not exist on type 'JasmineTestEnv'.
allure-jasmine: test/step.test.ts(75,17): error TS2339: Property 'it' does not exist on type 'JasmineTestEnv'.
```

**Comment by pavelfeldman** [comment]
@baev ^^

**Comment by pavelfeldman** [comment]
It should build/test now, but mocha coverage fails for me locally...

**Comment by pavelfeldman** [comment]
Your eslint is quite unusual, but should be aligned now.

**Comment by baev** [comment]
@pavelfeldman 

```
> allure-playwright@2.0.0-beta.10 test /home/runner/work/allure-js/allure-js/packages/allure-playwright
> playwright test -c test

·undefined
F···

  1) screenshot-on-failure.spec.ts:19:1 › should capture screenshot on failure =====================

    Error: expect(received).toEqual(expected) // deep equality

    - Expected  - 7
    + Received  + 1

    - Array [
    -   Object {
    -     "file": "/home/runner/work/allure-js/allure-js/packages/allure-playwright/test-results/screenshot-on-failure-should-capture-screenshot-on-failure/test-results/a-test-name/test-failed-1.png",
    -     "name": "screenshot",
    -     "type": "image/png",
    -   },
    - ]
    + Array []

      42 |     },
      43 |   );
    > 44 |   expect(result).toEqual([
         |                  ^
      45 |     {
      46 |       name: "screenshot",
      47 |       type: "image/png",

        at /home/runner/work/allure-js/allure-js/packages/allure-playwright/test/screenshot-on-failure.spec.ts:44:18
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/allure-js/allure-js/node_modules/@playwright/test/lib/test/workerRunner.js:390:7)


  1 failed
    screenshot-on-failure.spec.ts:19:1 › should capture screenshot on failure ======================
  4 passed (8s)
```

**Comment by pavelfeldman** [comment]
@baev that test was running full Playwright and we need to install browser deps and/or include GH action for that. That's one line in yaml, but I removed the test for now to unblock it as is.

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@pavelfeldman @just-boris thanks!

**Pull request merged**
