### PR TITLE
Add Cypress reports for skipped tests (fixes #948)

### LINKED ISSUE #948: support Cypress pending (skipped) tests
**Is your feature request related to a problem? Please describe.**
I would like to use allure reports to track the number of skipped cypress tests in my projects. My team tends to skip tests instead of fixing the underlying issues so we need a way to track number of skipped tests so they don't pile up ad infinitum.

**Describe the solution you'd like**
Ideally, the solution would reuse the existing `allureReportTest` task. I believe the issue is that the [afterEach hook](https://docs.cypress.io/guides/references/best-practices#Using-after-Or-afterEach-Hooks) does not run for tests that are explicitly skipped (cypress calls these 'pending').

### PR DESCRIPTION
**Pull request by RobertBattaglia**
### Context

Attempt to report Cypress skipped tests. Since skipped tests don't execute the `afterEach` hook, create a start and end message for each skipped test and execute `allureReportTest` task in the `after` hook.

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure-js

### CODE REVIEW

**Review by baev — APPROVED** [review]

**Review by epszaw — APPROVED** [review]

**Comment by epszaw** [comment]
Hey, @RobertBattaglia! Thank you for the contribution. Could you please run `prettier:format` and `lint:fix` scripts to fix the failed jobs?

**Comment by RobertBattaglia** [comment]
> Hey, @RobertBattaglia! Thank you for the contribution. Could you please run `prettier:format` and `lint:fix` scripts to fix the failed jobs?

done!

**Comment by RobertBattaglia** [comment]
> @RobertBattaglia could you please rebase it?

done, still haven't been able to figure out why that unit test is failing, I am having trouble running the tests locally

**Comment by epszaw** [comment]
Hey, @RobertBattaglia! We're working hard now on the new version, so it was much simpler to mo to cherry-pick your commits and solve the conflicts. I closed the PR because I had opened a new one (#1029). Thank you for the contributions!

**Pull request closed without merging**
