### PR TITLE
(fix): Mark test as failed when a request error occurs

### LINKED ISSUE #649: Newman - Test case status is passed even with failed steps
**Describe the bug**
Sometimes, on our gitlab CI pipeline, we saw on allure that all tests are passed, but when we looks in detail, we see that the steps failed

**To Reproduce**
Hard to reproduce as we do not have any clue on what's happend here, but you can have information in the zip file below and in the CLI console log.

**Expected behavior**
If a step failed, we should have a failed test case

**Screenshots**
Capture d’écran du 2023-03-27 10-04-09

**Additional context**
Here are some information about how our pipeline works : 
We execute different newman collection with the newman-allure-reporter package (we also add this parameter : --reporter-allure-collection-as-parent-suite).
All of the newman command populate the allure-results directory.

After the execution is done, we run the generation of the allure-results and see the difference.
We also have a htmlextra reporter which indicate the good status.
[report.zip](https://github.com/allure-framework/allure-js/files/11098691/report.zip)

### PR DESCRIPTION
**Pull request by matthrobin**
### Context

When a request error occured, the test was marked as "passed" instead of "failed".

Should fix #649 

Results exemple (anonymised for privacy): 
Allure-request-error

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by vovsemenv** [comment]
Hello! Big thanks for the contribution. Can you also add some cases for this case? I can help with it

**Comment by matthrobin** [comment]
> Hello! Big thanks for the contribution. Can you also add some cases for this case? I can help with it

You're welcome ! What do you mean by "add some cases for this case" ? Cases when a request error can occurs ?

**Comment by vovsemenv** [comment]
> Cases when a request error can occurs ?

Yes, you can create some mock requests and reproduce request errors as in existing tests

**Comment by matthrobin** [comment]
> > Cases when a request error can occurs ?
> 
> Yes, you can create some mock requests and reproduce request errors as in existing tests

Done !

**Review by baev — APPROVED** [review]

**Comment by vovsemenv** [comment]
Ok, I did a deeper look and have a question. Did we actually need to fail test when request is failed?
I guess passed test with failed request is a valid scenario when you check for example that API send error for the unauthorized users @matthrobin

**Comment by matthrobin** [comment]
> Ok, I did a deeper look and have a question. Did we actually need to fail test when request is failed? I guess passed test with failed request is a valid scenario when you check for example that API send error for the unauthorized users @matthrobin

I think that a request failing due to a network (unknow host, unreachable host, ...) or a timeout issue should not be "PASSED" because this can lead to unwanted situations. In your example, if you want to check for an unauthorized user i think the best way is to add an assertion on the returned HTTP code (401/403). 
What do you think about setting the status to "BROKEN" instead of "PASSED" like it is done in the [playwright reporter](https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/src/index.ts#L363). It would be great for consistency purposes.

**Review by baev — APPROVED** [review]

**Comment by matthrobin** [comment]
@vovsemenv What do you think about the latest changes ?

**Review by vovsemenv — APPROVED** [review]
Looks good, LGTM

**Comment by matthrobin** [comment]
> @baev merge pls

Hello ! Any news about this pull request  ?

**Comment by epszaw** [comment]
@matthrobin could you please resolve the conflicts?

**Comment by matthrobin** [comment]
> @matthrobin could you please resolve the conflicts?

I had some issues while resolving the conflicts. Reopned another pull request. Please see https://github.com/allure-framework/allure-js/pull/806

**Pull request closed without merging**
